---
- name: Install Docker on Ubuntu (ensure you run a suitable kernel)
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks:
    - name: 'Install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Upgrade list
      copy: content="deb https://apt.dockerproject.org/repo ubuntu-xenial main" dest=/etc/apt/sources.list.d/docker.list

    - name: apt-get update
      apt: update_cache=yes

    - name: Install dependencies
      apt: name={{ item }} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Install repo key
      command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: apt-get update
      apt: update_cache=yes

    - name: Install Docker
      apt: name={{ item }} state=installed
      with_items:
        - docker-engine

    - name: Generate certificates
      docker_cert_install:
        cert_dir: "/etc/docker/"
        cacert_path: "/etc/docker/ca.pem"
        caprivate_path: "/etc/docker/ca-key.pem"
        servercert_path: "/etc/docker/server.pem"
        servercertkey_path: "/etc/docker/server-key.pem"

    - name: Configure Docker
      template: src=etc/docker.service dest=/etc/systemd/system/docker.service owner=root group=root mode="u=rw,g=r,o=r"

    - name: Launch Docker
      systemd: name=docker state=started
